In [1]:
import numpy as np

In [2]:
a = np.zeros(10)

In [3]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.array([np.arange(0,3,1),np.arange(3,6,1),np.arange(6,9,1)])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.random.randn(5,5)

array([[-0.09374547,  0.9760664 ,  1.86364628,  1.63941633, -0.97318199],
       [ 2.01051027,  0.22455991, -1.11803294, -0.24113961,  0.96155681],
       [-1.14516575, -0.66748596,  0.64150631, -0.51220662,  1.70124942],
       [ 0.483785  ,  0.53868921, -0.9634188 ,  0.34707902, -0.25649978],
       [ 1.775827  ,  0.90276297,  1.01735193, -0.90908224, -0.03036751]])

In [11]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [12]:
np.arange(0,1.05,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [13]:
np.random.randint(25,size=(1,25))

array([[22,  7, 14,  3,  5,  1, 15, 18, 15, 21,  1,  0, 20, 16, 22,  7,
         6, 22,  1, 21,  8,  8,  0, 24, 20]])

In [14]:
b = np.random.randint(25,size=(1,25)).reshape(5,5)

In [15]:
b

array([[21,  8,  7, 19,  0],
       [22, 20, 19,  4, 14],
       [10, 22, 20,  5, 24],
       [12, 22, 11, 22, 13],
       [14, 11,  1, 24, 12]])

In [16]:
b.sum()

357

In [17]:
b.mean()

14.28

In [18]:
np.std(b)

7.208439498254806

In [19]:
b.sum(0)

array([79, 83, 58, 74, 63])

In [20]:
c = b.sum(axis=0)

In [21]:
d=np.random.randint(0,100,size=(5,5))

In [22]:
print(d)

[[96 42  8  5  5]
 [19 66 93 52 71]
 [45  6 43 21 44]
 [ 6 30 96 53  3]
 [91 87 93 25 51]]


In [23]:
np.median(d)

44.0

In [24]:
d.min()

3

In [25]:
d.max()

96

In [26]:
e=np.random.randint(0,100,size=(3,4))

In [27]:
print(e)

[[59 16 73 54]
 [54 14 84 33]
 [48 49  9 52]]


In [28]:
np.transpose(e)

array([[59, 54, 48],
       [16, 14, 49],
       [73, 84,  9],
       [54, 33, 52]])

In [29]:
f=np.random.randint(0,100,size=(3,4))

In [30]:
f

array([[26,  6, 80, 40],
       [39, 24, 87, 76],
       [69,  5, 34, 69]])

In [31]:
np.add(e,f)

array([[ 85,  22, 153,  94],
       [ 93,  38, 171, 109],
       [117,  54,  43, 121]])

In [32]:
np.multiply(e,f)

array([[1534,   96, 5840, 2160],
       [2106,  336, 7308, 2508],
       [3312,  245,  306, 3588]])

In [ ]:
g=np.transpose(e)

In [ ]:
g.shape


In [ ]:
np.matmul(e,g)